version: '3'
services:
  db:
    build: docker/db
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  backend:
    build: docker/backend
    volumes:
        - ./kotlin.web.demo.backend/build/libs/WebDemoBackend.war:/usr/local/tomcat/webapps/ROOT.war
  frontend:
    build: docker/frontend
    ports:
        - 80:80
        - 443:443
        - 8080:8080
        - 8443:8443
    volumes:
        - ./kotlin.web.demo.server/build/libs/WebDemoWar.war:/usr/local/tomcat/webapps/ROOT.war
    depends_on:
        - db
        - backend
