name: Deployment of TryArrow in AWS

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Starting the deployment
      env: # Or as an environment variable
        AWS_TRY_ARROW_PEM: ${{ secrets.AWS_TRY_ARROW_PEM }}
        AWS_EC2_IP_ADDRESS: ${{ secrets.AWS_EC2_IP_ADDRESS }}
      run: |
        echo $AWS_TRY_ARROW_PEM | base64 --decode > try.arrow-kt.pem
        chmod 400 ./try.arrow-kt.pem
        scp -o "StrictHostKeyChecking no" -q -i ./try.arrow-kt.pem deploy.sh $AWS_EC2_IP_ADDRESS:~/deploy.sh
        ssh -o "StrictHostKeyChecking no" -q -i ./try.arrow-kt.pem $AWS_EC2_IP_ADDRESS 'sh deploy.sh; exit'
